# Generated by Django 5.1.7 on 2025-03-08 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(max_length=500)),
                ('summary', models.CharField(max_length=500)),
                ('bullets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None)),
            ],
        ),
    ]
