# Generated by Django 5.1.7 on 2025-03-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='input_text',
            field=models.TextField(),
        ),
    ]
