# Generated by Django 5.1.7 on 2025-03-08 19:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_text_input_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='bullets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='text',
            name='summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
