# Generated by Django 5.1.7 on 2025-03-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_text_bullets_alter_text_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='input_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='text',
            name='summary',
            field=models.TextField(default='', null=True),
        ),
    ]
